image: fedora:rawhide
stages:
  - check
  - build
  - deploy

variables:
  DEPENDENCIES: python3 gobject-introspection-devel gtk3-devel libmediaart-devel grilo-devel

build:
  stage: build
  script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
    - git submodule update --init
    - ./autogen.sh
    - make

deploy:
  stage: deploy
  script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
    - git submodule update --init
    - ./autogen.sh
    - make distcheck
    - export VERSION=$(git describe --abbrev=0 --tags)
    - export RELEASE="$(date +"%Y%m%d")git$(git rev-parse --short=8 HEAD)"
    - echo "Making a fedora copr build"
    - mkdir -p /root/rpmbuild/SOURCES
    - cp gnome-music-*.tar.xz /root/rpmbuild/SOURCES/gnome-music-$VERSION.tar.xz
    - cd /root
    - git clone git://pkgs.fedoraproject.org/gnome-music.git
    - cd gnome-music
    - sed -i "s,Version:.*,Version: $VERSION," gnome-music.spec
    - sed -i "s,Release:.*,Release: $RELEASE%{?dist}," gnome-music.spec
    - rpmbuild -bs gnome-music.spec
    - ls -la /root/rpmbuild/SRPMS/*.src.rpm
  only:
    - tags

pyflakes:
  stage: check
  script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck python3-pyflakes
    - python3-pyflakes .

pep8:
  stage: check
  script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck python3-pep8
    - python3-pep8 --ignore=E501,E225,E265,E402 --show-source --show-pep8 .
  allow_failure: true