sudo: required
services: docker
language: python
env:
- TEST="pyflakes"
- TEST="pep8"
- TEST="build"
matrix:
  allow_failures:
  - env: TEST="pep8"
before_install:
- openssl aes-256-cbc -K $encrypted_82d618340c6b_key -iv $encrypted_82d618340c6b_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- docker run -e "PR=$TRAVIS_PULL_REQUEST" -itv $(pwd):/mnt --rm fedora:rawhide "/bin/sh"
  "/mnt/ci_$TEST.sh"
